config/routes.rb
Hall::Application.routes.draw do
  resources :rooms do
    member do
      post 'add_message'
    end
  end

  devise_for :users

  match '*paths' => 'main#index'
  root :to => 'main#index'

end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :user
  attr_accessible :name, :token, :session_id
  before_create :generate_token!

  protected
  def generate_token!
  	self.token = SecureRandom.hex(3)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :token_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :rooms

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
  								:name, :avatar
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_filter :authenticate_user!
  respond_to :json, :html
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = current_user.rooms

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rooms }
    end
  end

  # GET /rooms/:token
  # GET /rooms/:token.json
  def show
    @room = Room.find_by_token(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @room }
    end
  end

  def join
    @room = Room.where(token: params[:token])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @room }
    end
  end

  def get_token
    api_key = Settings.opentok.api_key
    api_secret = Settings.opentok.api_secret

    opentok = OpenTok::OpenTokSDK.new api_key, api_secret
    session = opentok.create_session request.remote_addr

    token = opentok.generate_token :session_id => session, :role => OpenTok::RoleConstants::PUBLISHER, :connection_data => "username=#{current_user.email}"
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: token }
    end
  end

  def add_message
    require 'pusher'

    Pusher.app_id = '11733'
    Pusher.key = '29bf925ddf5d74c2f83f'
    Pusher.secret = '0369c29389469fc0540a'

    Pusher["public-chat-#{params[:id]}"].trigger('new_message', 
      {sender: params[:sender], message: params[:message]}, params[:socket_id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { head :no_content }
    end
  end

  # GET /rooms/new
  # GET /rooms/new.json
  def new
    @room = Room.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = current_user.rooms.new(params[:room])
    api_key = Settings.opentok.api_key
    api_secret = Settings.opentok.api_secret

    opentok = OpenTok::OpenTokSDK.new api_key, api_secret 
    session_properties = {OpenTok::SessionPropertyConstants::P2P_PREFERENCE => "disabled"}
    session = opentok.create_session request.remote_addr, session_properties

    @room[:session_id] = session.session_id

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render json: @room, status: :created, location: @room }
      else
        format.html { render action: "new" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rooms/1
  # PUT /rooms/1.json
  def update
    @room = Room.find(params[:id])

    respond_to do |format|
      if @room.update_attributes(params[:room])
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room = Room.find(params[:id])
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Talkee</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "http://js.pusher.com/1.12/pusher.min.js" %>
  <%= javascript_include_tag "application" %>

  <% # Start the app %>
  <script type="text/javascript">
    <% if user_signed_in? %>
      App.currentUser = new App.Models.User(<%=j current_user.to_json.html_safe %>);
    <% end %>

    $(document).ready(function(){
      App.otKey = "<%= Settings.opentok.api_key %>";
      App.start()
    });
  </script>

  <%= csrf_meta_tags %>
</head>
<body>

<div id="app">
	<%= yield %>
</div>

<% # App Notifications %>
<script type="text/javascript">
  <% if alert %>
	 App.notifier.notify("<%= alert %>");
  <% end %>

  <% if notice %>
    App.notifier.notify("<%= notice %>");
  <% end %>
</script>

</body>
</html>

app/views/main/index.html.erb
<h1>Welcome to Hall</h1>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :token %><br />
    <%= f.text_field :token %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<h1>Listing rooms</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Token</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rooms.each do |room| %>
  <tr>
    <td><%= room.name %></td>
    <td><%= room.token %></td>
    <td><%= room.user %></td>
    <td><%= link_to 'Show', room %></td>
    <td><%= link_to 'Edit', edit_room_path(room) %></td>
    <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @room.name %>
</p>

<p>
  <b>Token:</b>
  <%= @room.token %>
</p>

<p>
  <b>User:</b>
  <%= @room.user %>
</p>


<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>